#!/usr/bin/env ruby

require "bundler/setup"
require "ruby_ruby"

if ARGV.empty?
  source, filename = STDIN.read, "$stdin"
else
  source, filename = File.read(ARGV.first), ARGV.first
end

puts RubyRuby.run(source, filename)
