#!/usr/bin/env ruby

require "bundler/setup"
require "ruby_ruby"

if ARGV.empty?
  input, filename = STDIN.read, "$stdin"
else
  input, filename = File.read(ARGV.first), ARGV.first
end

puts RubyRuby::Lexer.new(input, filename).tokens